org.gradle.jvmargs=-Xmx8192M
org.gradle.deamon=false

# Project
version=1.3.0
group=net.xstopho.resource_backpacks
java_version=21
modrinth_id=t8iyhYu7
curseforge_id=971140

# Common
mod_name=Resource Backpacks
mod_author=xStopho
mod_id=resource_backpacks
mod_license=MIT
mod_description=Yet another mod, that aims to bring simple upgradable backpacks to Minecraft.
mod_credits=

# Dependencies
resource_config_api=3.8.1
resource_library=2.9.2