org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

# Project
version=0.13.5-BETA
group=net.xstopho.resource_backpacks
java_version=21
modrinth_id=t8iyhYu7
curseforge_id=971140

# Common
mod_name=Resource Backpacks
mod_author=xStopho
mod_id=resource_backpacks
mod_license=MIT
mod_credits=
mod_description=Yet another mod, that aims to bring simple upgradable backpacks to Minecraft.