plugins {
    id 'net.neoforged.moddev'
}

repositories {
    maven { url 'https://raw.githubusercontent.com/Stein-N/resources/main/maven' }
}

dependencies {
    implementation(project(":1.21.1:common"))
    implementation "net.xstopho.resourceconfigapi:resourceconfigapi-neoforge:${resource_config_api}"
    implementation "net.xstopho.resourcelibrary:resourcelibrary-neoforge:${resource_library}"
}

compileJava {
    source(project(':1.21.1:common').sourceSets.main.allSource)
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }

    runs {
        data {
            data()
            ideName = "Common Datagen (1.21.1)"
            gameDirectory = file('../common/runs/data')
            programArguments = ['--mod', project.mod_id, '--all', '--output', file('../common/src/generated/').getAbsolutePath(), '--existing', file('../common/src/main/resources/').getAbsolutePath()]
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}